### ISSUE TITLE
Rokujo and Mishiro's rankings doesn't show up right

### ISSUE THREAD

**Issue by Isshou** [sorvani/dgenesisinfo#4]
They now have multiple ranking lines with newer date entries, yet they still show up in the ranking list as 'Unknown'.

![image](https://github.com/user-attachments/assets/fda1dcbb-2841-4137-9f0e-c52d18015635)

I think there's something odd in the sort/conversion of the short date vs the unix time.

Should date be enforced to be unix time? only have one ranking entry?

**Comment by sorvani** [comment]
fixed by a5b8535a3d494bd4c112e16bbdbf45c2ef0fb933
